server:
  port: ${PORT:9000}

spring:
  application:
    name: BANKING-SYSTEM
  main:
    lazy-initialization: true
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/banking_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:Ramesh@2002}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false

jwt:
  secret: ${JWT_SECRET:bankingsystemsecretkey1234567890abcdefghij}
  expiration: 86400000

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
    version: OPENAPI_3_0
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    disable-swagger-default-url: true