name: Specmatic CI

on:
  push:
  pull_request:

jobs:
  contract-tests:
    name: Contract Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Run Contract Tests
        run: ./mvnw test -Dtest=BankingContractTest -Dspring.profiles.active=test
        continue-on-error: true

      - name: Upload Contract Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: contract-report
          path: build/reports/specmatic/

  resiliency-tests:
    name: Resiliency Tests
    runs-on: ubuntu-latest
    needs: contract-tests

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Run Resiliency Tests
        run: ./mvnw test -Dtest=BankingContractTest -Dspring.profiles.active=test
        continue-on-error: true

      - name: Upload Resiliency Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: resiliency-report
          path: build/reports/specmatic/
